POST http://localhost:4000/api/item
Content-Type: application/json

{
  "item": "This is the test vala todo",
  "completed":true
}

###

GET http://localhost:4000/api/items
Content-Type: application/json

###

PUT http://localhost:4000/api/item/6245bfd3eb7b72345090f275
Content-Type: application/json

{
  "item": "This is the second todo item updated!!"
}

###

DELETE  http://localhost:4000/api/item/6245bad3eb7b72345090f273
Content-Type: application/json
